version: "3.3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vF0hHOy2kKT21NPSJD4CrPfV
      MYSQL_DATABASE: utils
      MYSQL_USER: utils_user
      MYSQL_PASSWORD: zb7JNlMKW8CMj65BVJekAOaz

  service:
    depends_on:
      - mysql
    image: localhost:5000/utils-be
    volumes:
      - app_data:/app/work/
    ports:
      - "8100:8080"
    restart: always
    environment:
      QUARKUS_DATASOURCE_DB_KIND: mysql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/utils
      QUARKUS_DATASOURCE_USERNAME: utils_user
      QUARKUS_DATASOURCE_PASSWORD: zb7JNlMKW8CMj65BVJekAOaz

volumes:
  db_data: {}
  app_data: {}

networks:
  bridge:
