version: "3.3"

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: utils_user
      MONGO_INITDB_ROOT_PASSWORD: vF0hHOy2kKT21NPSJD4CrPfV

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vF0hHOy2kKT21NPSJD4CrPfV
      MYSQL_DATABASE: contabo_utils
      MYSQL_USER: utils_user
      MYSQL_PASSWORD: zb7JNlMKW8CMj65BVJekAOaz

  service:
    depends_on:
      - mysql
      - mongo
    image: localhost:5000/utils
    volumes:
      - app_data:/app/work/
    ports:
      - "8100:8080"
    restart: always
    environment:
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: utils_user
      MYSQL_DB_PASSWORD: zb7JNlMKW8CMj65BVJekAOaz
      MYSQL_DB_NAME: contabo_utils
      MONGO_DB_HOST: mongo:27017
      MONGO_DB_PASSWORD: vF0hHOy2kKT21NPSJD4CrPfV

volumes:
  db_data: {}
  mongo_data: {}
  app_data: {}
