pipeline 
{
    agent {
        any{}
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build Native Executable') {
            steps {
                sh 'mvn package -Pnative -Dquarkus.native.container-build=true'
            }
        }
        stage('Build Container From Native Executable') {
            steps {
                sh 'docker build -f src/main/docker/Dockerfile.native -t localhost:5000/utils-native .'
            }
        }
        stage('Kill Old Instances') {
            steps {
                sh 'docker rm -f utils-native || true'
            }
        }
        stage('Kill Docker Compose Infrastructure') {
            steps {
                sh 'docker-compose -f utilsNativeStack.yml kill'
            }
        }
        stage('Run Docker Image in Native Mode') {
            steps {
                sh 'docker run -d --network utils-infrastructure -p 8101:8080 --name utils-native localhost:5000/utils-native'
            }
        }
        // stage('START Docker Compose Infrastructure') {
        //     steps {
        //         sh 'docker-compose -f utilsNativeStack.yml up -d'
        //     }
        // }
    }
}