pipeline {
    agent {
        any{}
    }
    options {
        skipStagesAfterUnstable()
    }
    environment {
        DB_1_KIND = "postgresql"
        DB_1_JDBC_URI = "jdbc:postgresql://207.180.212.110:54322/utils"
        DB_1_USERNAME="utils_user"
        DB_1_PASSWORD="utils_user"
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    properties([pipelineTriggers([pollSCM('')])])
                }
                git branch: 'master', credentialsId: 'git-cred', url: 'https://github.com/aldolushkja/utils-be.aldolushkja.it.git'
            }
        }
        stage('Package and build Docker image') {
            steps {
                sh 'mvn clean package && docker build -f src/main/docker/Dockerfile.jvm -t localhost:5000/utils-be .'
            }
        }
        // stage('Build executable jar') {
        //     steps {
        //         sh 'mvn clean package'
        //     }
        // }
        // stage('Launch executable jar') {
        //     steps {
        //         sh 'java -Dquarkus.datasource.db-kind=${DB_1_KIND}  -Dquarkus.datasource.username=${DB_1_USERNAME} -Dquarkus.datasource.password=${DB_1_PASSWORD} -Dquarkus.datasource.jdbc.url=${DB_1_JDBC_URI} -jar target/quarkus-app/quarkus-run.jar &'
        //     }
        // }
        stage('Run docker image') {
            steps {
                sh 'docker run -i --rm -p 6080:8080 localhost:5000/utils-be \
                -e quarkus.datasource.db-kind=${DB_1_KIND} \
                -e quarkus.datasource.username=${DB_1_USERNAME} \
                -e quarkus.datasource.password=${DB_1_PASSWORD} \
                -e quarkus.datasource.jdbc.url=${DB_1_JDBC_URI} \
                -n utils-be localhost:5000/utils-be'
            }
        }
    }
}