pipeline {
    agent {
        any{}
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build Jar Executable') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Build Container From Executable JAR') {
            steps {
                sh 'docker build -f src/main/docker/Dockerfile.jvm -t localhost:5000/utils .'
            }
        }
        stage('Kill Old Instances') {
            steps {
                sh 'docker rm -f utils || true'
            }
        }
        // stage('Kill Docker Compose Infrastructure') {
        //     steps {
        //         sh 'docker-compose -f utilsStack.yml kill'
        //     }
        // }
        stage('Run Docker Image in JVM Mode') {
            steps {
                sh 'docker run -d --network=utils-infrastructure -p 8100:8080 --name utils localhost:5000/utils'
            }
        }
        // stage('START Docker Compose Infrastructure') {
        //     steps {
        //         sh 'docker-compose -f utilsStack.yml up -d'
        //     }
        // }
    }
}